version: "3.9"
services:
  nginx:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - reactapp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    networks:
      - hackathon_spring_network
    ports:
      - 80:80
  reactapp:
    build:
      context: ./front
      args:
        - MY_UID=${MY_UID}
        - MY_GID=${MY_GID}
        - PORT_VITE=${PORT_VITE}
    env_file:
      - .env
    networks:
      - hackathon_spring_network
    volumes:
      - ./front:/home/appuser/devcon
    # ports:
    #   - ${PORT_VITE}:${PORT_VITE}
    expose:
      - ${PORT_VITE}
    command: ["/bin/bash", "-c", "/home/appuser/devcon/build.sh"]

  fastapi:
    build:
      context: ./flask_back/apis
      args:
        - MY_UID=${MY_UID}
        - MY_GID=${MY_GID}
        - PORT_FAST=${PORT_FAST}
    volumes:
      - ./flask_back:/home/appuser/devcon
    env_file:
      - .env
    networks:
      - hackathon_spring_network
    ports:
      - ${PORT_FAST}:${PORT_FAST}
    # expose:
    #   - ${PORT_FAST}
    command: ["/bin/sh", "-c", "/home/appuser/devcon/build.sh"]

  mysql_fast:
    build:
      context: ./flask_back//mysql
      args:
        - PORT_MYSQL_FAST=${PORT_MYSQL_FAST}
        - MYSQL_USER=${MYSQL_USER}
    volumes:
      - ./flask_back//mysql/data/db:/var/lib/mysql/${MYSQL_DB_FAST}
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env
    networks:
      - hackathon_spring_network
    # ports:
    #   - ${PORT_MYSQL_FAST}:${PORT_MYSQL_FAST}
    expose:
      - ${PORT_MYSQL_FAST}

  pma_fast:
    build:
      context: ./flask_back/phpmyadmin
      args:
        PORT_PMA_FAST: ${PORT_PMA_FAST}
    env_file:
      - .env
    networks:
      - hackathon_spring_network
    environment:
      PMA_HOST: ${MYSQL_HOST_FAST}
      PMA_PORT: ${PORT_MYSQL_FAST}
    # expose:
    #   - ${PORT_PMA_FAST}
    ports:
      - ${PORT_PMA_FAST}:${PORT_PMA_FAST}
    volumes:
      - ./flask_back/phpmyadmin/sessions:/sessions

networks:
  hackathon_spring_network:
    name: hackathon_spring_network
